export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const RESET_STATE = 'RESET_STATE';
export const SET_USER = 'SET_USER';

export const LoginState = {
    INITIAL: 'INITIAL',
    LOADED_CREDENTIALS: 'LOADED_CREDENTIALS',
    LOADING: 'LOADING',
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_OUT: 'LOGGED_OUT',
    FAILED: 'FAILED',
    NETWORK_ERROR: 'NETWORK_ERROR'
};